Main svc
steelzhi/java-explore-with-me pull request #2
Opened 2023-07-30 16:10 UTC by steelzhi

Добавить основной сервис

2023-07-30 17:09 UTC, steelzhi commented
Никита, здравствуйте.
Задание этапа 2 дипломного проекта я выполнил - проверьте, пожалуйста.

2023-07-31 09:41 UTC, mikita95 requested changes
Все сделано хорошо. Оставил лишь несколько замечаний

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/client/EventClient.java
> +    @Transactional
Здесь нет запросов к базе данных, поэтому Transactional не нужно

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/client/EventClient.java
> +    @Transactional
Здесь нет запросов к базе данных, поэтому Transactional не нужно

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/dto/CategoryDto.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Кажется, что здесь это не нужно

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/dto/CompilationDto.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Кажется, что здесь это не нужно

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/dto/EventFullDto.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Кажется, что здесь это не нужно

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/dto/EventRequestStatusUpdateRequest.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Кажется, что здесь это не нужно

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/dto/EventRequestStatusUpdateResult.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Кажется, что здесь это не нужно

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/model/Category.java
> +@Data
Data не рекомендуется использовать над hibernate сущностями, так как это генерирует hashCode и equals, которые могут начать вызывать lazy поля или создать циклическую зависимость

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/model/Category.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Этот класс не должен сохраняться как json, это здесь не нужно

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/model/Category.java
> +@Data
Аналогично в других сущностях

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/service/CategoryServiceImpl.java
> +    @Transactional
Здесь можно использовать флаг readOnly

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/service/CategoryServiceImpl.java
> +    @Transactional
Здесь можно использовать флаг readOnly

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/service/CategoryServiceImpl.java
> +        if (newCategoryDto.getName().length() > 50) {
Магическое число лучше вынести в константы

2023-07-31 09:41 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/ewm/service/CompilationServiceImpl.java
> +    @Transactional
Здесь можно использовать флаг readOnly

2023-07-31 16:05 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/client/EventClient.java
> +    @Transactional
Да, не подумал. Убрал.

2023-07-31 16:05 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/client/EventClient.java
> +    @Transactional
Убрал.

2023-07-31 16:07 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/dto/CategoryDto.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Убрал лишние аннотации @Builder и @JsonIgnoreProperties. @AllArgsConstructor и @NoArgsConstructor оставил - они нужны. Также @Data заменил на @Getter и @Setter.

2023-07-31 16:07 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/dto/CompilationDto.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Убрал лишние аннотации @Builder и @JsonIgnoreProperties. @AllArgsConstructor и @NoArgsConstructor оставил - они нужны. Также @Data заменил на @Getter и @Setter.

2023-07-31 16:07 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/dto/EventFullDto.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Убрал лишние аннотации @Builder и @JsonIgnoreProperties. @AllArgsConstructor и @NoArgsConstructor оставил - они нужны. Также @Data заменил на @Getter и @Setter.

2023-07-31 16:07 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/dto/EventRequestStatusUpdateRequest.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Убрал лишние аннотации @Builder и @JsonIgnoreProperties. @AllArgsConstructor и @NoArgsConstructor оставил - они нужны. Также @Data заменил на @Getter и @Setter.

2023-07-31 16:08 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/dto/EventRequestStatusUpdateResult.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Убрал лишние аннотации `@Builder` и `@JsonIgnoreProperties`. `@AllArgsConstructor` и `@NoArgsConstructor` оставил - они нужны. Также `@Data` заменил на `@Getter` и `@Setter`.

2023-07-31 16:10 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/model/Category.java
> +@Data
Понял, спасибо. Заменил `@Data` на `@Getter` и `@Setter` (в этой и остальных сущностях).

2023-07-31 16:11 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/model/Category.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Убрал `@JsonIgnoreProperties`.

2023-07-31 16:15 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/service/CategoryServiceImpl.java
> +    @Transactional
Добавил флаг в этом методе, а также в других методах чтения.

2023-07-31 16:15 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/service/CategoryServiceImpl.java
> +    @Transactional
Добавил флаг.

2023-07-31 16:27 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/service/CategoryServiceImpl.java
> +        if (newCategoryDto.getName().length() > 50) {
В этом и в других сервисах вынес все магические числа в константы.

2023-07-31 16:27 UTC, steelzhi commented on main-service/src/main/java/ru/practicum/ewm/service/CompilationServiceImpl.java
> +    @Transactional
Добавил флаг.

2023-07-31 17:05 UTC, steelzhi commented
Никита, здравствуйте.
Спасибо за ревью. Ваши замечания поправил - проверьте, пожалуйста.
P.S. Стандартное наименование констант не проходит проверку Checkstyle на Github (в Checkstyle задан неправильный regex - ^[a-z][a-zA-Z0-9]*$). Поэтому имена констант пришлось написать маленькими буквами, без подчеркиваний (иначе не получалось пройти проверку).

2023-08-01 13:40 UTC, mikita95 approved these changes
Всё хорошо. Можно мержить пул-реквест

2023-08-02 15:25 UTC, merged